name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .github/environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'

      - name: Install OpenMC
        shell: bash
        run: |
          micromamba activate test-env
          micromamba install -c conda_forge openmc==0.15.0

      - name: Clone OpenMC
        run: |
          git clone https://github.com/openmc-dev/openmc --branch v0.15.0 $HOME


      - name: Test examples
        shell: bash
        run: |
          micromamba activate test-env
          OPENMC_EXAMPLES_DIR=$HOME/openmc/examples pytest -v ./test/test_examples.py

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
